<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_placeOrder</name>
   <tag></tag>
   <elementGuidId>fad24059-63ee-4c0b-862f-1ab0c0d80df2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;page-wrapper&quot;]/div/div[2]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;page-wrapper&quot;]/div/div[2]/button</value>
      <webElementGuid>f9028c20-d1f7-4f74-bb6a-a289737346a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>page-wrapper</value>
      <webElementGuid>60246fcb-c079-4d62-b8e6-3b4d2758658a</webElementGuid>
   </webElementProperties>
</WebElementEntity>
