<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_detailPurchase</name>
   <tag></tag>
   <elementGuidId>8344b5c1-1201-4380-9298-46b249f769ad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[10]/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[10]/p</value>
      <webElementGuid>c25c82e1-a448-4a30-a814-26f099682422</webElementGuid>
   </webElementProperties>
</WebElementEntity>
