<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_send_message</name>
   <tag></tag>
   <elementGuidId>8d36c64c-3abf-46aa-9fe4-0268149d8066</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;exampleModal&quot;]/div/div/div[3]/button[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;exampleModal&quot;]/div/div/div[3]/button[2]</value>
      <webElementGuid>cf617922-a262-4e9d-ab42-ed70d77f4abe</webElementGuid>
   </webElementProperties>
</WebElementEntity>
