<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_new_message</name>
   <tag></tag>
   <elementGuidId>b1c0b30f-3410-4af4-81a8-603e1b7a1b7b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;exampleModalLabel&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>exampleModalLabel</value>
      <webElementGuid>d9535b35-6a72-49fe-af75-f9e679c4df1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;exampleModalLabel&quot;]</value>
      <webElementGuid>a641539d-b073-44a1-808e-e1968f7d7dfd</webElementGuid>
   </webElementProperties>
</WebElementEntity>
