<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_login</name>
   <tag></tag>
   <elementGuidId>552d1292-fe9e-48ac-be82-9dd9378197ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;logInModal&quot;]/div/div/div[3]/button[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>logInModal</value>
      <webElementGuid>7d767755-162d-4082-a1ab-6acf864b3e8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;logInModal&quot;]/div/div/div[3]/button[2]</value>
      <webElementGuid>5e658d84-935a-46d6-aeb1-9c74a62613e3</webElementGuid>
   </webElementProperties>
</WebElementEntity>
